Add AS_XML serializatiion format support
Mange/roadie pull request #168
Opened 2021-06-08 15:10 UTC by kovalevsky

Sometimes we need to render html markup as xml. For instance, in my particular case i have to render inlined styles to RSS-feed and don't allowed to use self-closed tags. Tags like `<img src="..." />` broke some strict xml parsers.

2021-06-09 06:52 UTC, Mange commented
For RSS feeds it's common to wrap HTML content in `<![CDATA[…]]>` tags. That prevents errors from yours from happening.

Have you tried this?

2021-06-19 22:03 UTC, kovalevsky commented
@Mange yes sure. In my particular case the problem is on rss feed consumers side. The case is a bit specific, however, increasing flexibility of serialization might be helpful.

2021-06-24 10:18 UTC, Mange commented
I see. Well, the implementation isn't very big so I don't see any big harm in it.

2021-06-24 10:19 UTC, Mange requested changes

2021-06-24 10:19 UTC, Mange commented on spec/lib/roadie/document_spec.rb
> +          document.mode = :xhtml
You want to set this to `:xml`.

2021-06-24 10:19 UTC, Mange commented on spec/lib/roadie/document_spec.rb
> +          document.mode = :xhtml
Same here.

2021-06-24 14:10 UTC, kovalevsky commented on spec/lib/roadie/document_spec.rb
> +          document.mode = :xhtml
Thank you, fixed

2021-07-05 15:25 UTC, Mange approved these changes

2021-07-05 15:25 UTC, merged